plt.plot(N_values, jacobi_times, label='Metoda Jacobiego')
plt.plot(N_values, gauss_seidel_times, label='Metoda Gaussa-Seidela')
plt.xlabel('Wymiar N')
plt.ylabel('Czas (s)')
plt.yscale('log')
plt.legend()
plt.title('Czas rozwiązania w funkcji wymiaru N dla metod Jacobiego i Gaussa-Seidela')
plt.grid(True)
plt.show()