# Instrukcja uruchomienia
# Aby stworzyć wykres przedstawiający inteprolację dla różnej ilości węzłów należy użyć make wykres
# Aby stworzyć wykres przedstawiający błąd interpolacji należy użyć make error


wykres:
	python NUM7.py wykres

error:
	python NUM7.py error

