# Instrukcja uruchomienia
# Aby stworzyć wykres dla h z zakresu float należy użyć make wykres_f (powstaje plik wykres_f.svg)
# Aby stworzyć wykres dla h z zakresu double należy użyć make wykres_d (powstaje plik wykres_d.svg)
# Aby wypisać wartości błędów dla zakresu float należy użyć make blad_f
# Aby wypisać wartości błędów dla zakresu double należy użyć make blad_d

wykres_f:
	python NUM1.py float wykres

wykres_d:
	python NUM1.py double wykres

blad_f:
	python NUM1.py float blad

blad_d:
	python NUM1.py double blad