# Instrukcja uruchomienia
# Aby stworzyć wykres skłądajacy się z czterech mniejszych należy użyć make make show
# Aby stworzyć i zapisać cztery osobne wykresy należy użyć make save (powstają 4 pliki z wykresami)


show:
	python NUM6.py show

save:
	python NUM6.py save

